
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-19T17:37:50+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "775d01952330a9d2347c68ea137054d1cc7689cb",
 "version": "0.11.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
